server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exsecurity
    username: root
    password: root
  jpa:
    hibernate:
    ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        show_sql: true
  flyway:
    enabled: true
    locations: classpath:db.migration
    outOfOrder: true
springdoc:
  show-login-endpoint: true